<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="firozkhan" name="testClasses.SocialLogin" tests="7" failures="6" timestamp="20 Sep 2017 09:41:35 GMT" time="143.711" errors="0">
  <testcase name="gmailLogin" time="38.088" classname="testClasses.SocialLogin"/>
  <testcase name="twitterLogin" time="29.823" classname="testClasses.SocialLogin">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [Social Sign In | app.oneall.com] but found [Securely sign in to your account | app.oneall.com],
	expected [Social Sign In | app.oneall.com] but found [Securely sign in to your account | app.oneall.com]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
	expected [Social Sign In | app.oneall.com] but found [Securely sign in to your account | app.oneall.com],
	expected [Social Sign In | app.oneall.com] but found [Securely sign in to your account | app.oneall.com]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at testClasses.SocialLogin.twitterLogin(SocialLogin.java:90)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
    </failure>
  </testcase> <!-- twitterLogin -->
  <testcase name="twitterLogin" time="33.359" classname="testClasses.SocialLogin">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [Social Sign In | app.oneall.com] but found [Securely sign in to your account | app.oneall.com]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
	expected [Social Sign In | app.oneall.com] but found [Securely sign in to your account | app.oneall.com]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at testClasses.SocialLogin.twitterLogin(SocialLogin.java:90)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
    </failure>
  </testcase> <!-- twitterLogin -->
  <testcase name="linkdinLogin" time="10.154" classname="testClasses.SocialLogin">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [Social Sign In | app.oneall.com] but found [Securely sign in to your account | app.oneall.com],
	expected [Social Sign In | app.oneall.com] but found [Securely sign in to your account | app.oneall.com],
	expected [Social Sign In | app.oneall.com] but found [Securely sign in to your account | app.oneall.com],
	expected [Social Sign In | app.oneall.com] but found [Securely sign in to your account | app.oneall.com]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
	expected [Social Sign In | app.oneall.com] but found [Securely sign in to your account | app.oneall.com],
	expected [Social Sign In | app.oneall.com] but found [Securely sign in to your account | app.oneall.com],
	expected [Social Sign In | app.oneall.com] but found [Securely sign in to your account | app.oneall.com],
	expected [Social Sign In | app.oneall.com] but found [Securely sign in to your account | app.oneall.com]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at testClasses.SocialLogin.linkdinLogin(SocialLogin.java:111)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
    </failure>
  </testcase> <!-- linkdinLogin -->
  <testcase name="linkdinLogin" time="12.020" classname="testClasses.SocialLogin">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [Social Sign In | app.oneall.com] but found [Securely sign in to your account | app.oneall.com],
	expected [Social Sign In | app.oneall.com] but found [Securely sign in to your account | app.oneall.com],
	expected [Social Sign In | app.oneall.com] but found [Securely sign in to your account | app.oneall.com]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
	expected [Social Sign In | app.oneall.com] but found [Securely sign in to your account | app.oneall.com],
	expected [Social Sign In | app.oneall.com] but found [Securely sign in to your account | app.oneall.com],
	expected [Social Sign In | app.oneall.com] but found [Securely sign in to your account | app.oneall.com]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at testClasses.SocialLogin.linkdinLogin(SocialLogin.java:111)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
    </failure>
  </testcase> <!-- linkdinLogin -->
  <testcase name="facebookLogin" time="10.087" classname="testClasses.SocialLogin">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [Social Sign In | app.oneall.com] but found [Securely sign in to your account | app.oneall.com],
	expected [Social Sign In | app.oneall.com] but found [Securely sign in to your account | app.oneall.com],
	expected [Social Sign In | app.oneall.com] but found [Securely sign in to your account | app.oneall.com],
	expected [Social Sign In | app.oneall.com] but found [Securely sign in to your account | app.oneall.com],
	expected [Social Sign In | app.oneall.com] but found [Securely sign in to your account | app.oneall.com]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
	expected [Social Sign In | app.oneall.com] but found [Securely sign in to your account | app.oneall.com],
	expected [Social Sign In | app.oneall.com] but found [Securely sign in to your account | app.oneall.com],
	expected [Social Sign In | app.oneall.com] but found [Securely sign in to your account | app.oneall.com],
	expected [Social Sign In | app.oneall.com] but found [Securely sign in to your account | app.oneall.com],
	expected [Social Sign In | app.oneall.com] but found [Securely sign in to your account | app.oneall.com]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at testClasses.SocialLogin.facebookLogin(SocialLogin.java:51)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
    </failure>
  </testcase> <!-- facebookLogin -->
  <testcase name="facebookLogin" time="10.180" classname="testClasses.SocialLogin">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [Social Sign In | app.oneall.com] but found [Securely sign in to your account | app.oneall.com],
	expected [Social Sign In | app.oneall.com] but found [Securely sign in to your account | app.oneall.com],
	expected [Social Sign In | app.oneall.com] but found [Securely sign in to your account | app.oneall.com],
	expected [Social Sign In | app.oneall.com] but found [Securely sign in to your account | app.oneall.com],
	expected [Social Sign In | app.oneall.com] but found [Securely sign in to your account | app.oneall.com],
	expected [Social Sign In | app.oneall.com] but found [Securely sign in to your account | app.oneall.com]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
	expected [Social Sign In | app.oneall.com] but found [Securely sign in to your account | app.oneall.com],
	expected [Social Sign In | app.oneall.com] but found [Securely sign in to your account | app.oneall.com],
	expected [Social Sign In | app.oneall.com] but found [Securely sign in to your account | app.oneall.com],
	expected [Social Sign In | app.oneall.com] but found [Securely sign in to your account | app.oneall.com],
	expected [Social Sign In | app.oneall.com] but found [Securely sign in to your account | app.oneall.com],
	expected [Social Sign In | app.oneall.com] but found [Securely sign in to your account | app.oneall.com]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at testClasses.SocialLogin.facebookLogin(SocialLogin.java:51)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
    </failure>
  </testcase> <!-- facebookLogin -->
</testsuite> <!-- testClasses.SocialLogin -->
